version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - hotspot-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://hotspotuser:${DB_PASSWORD}@db:5432/hotspotdb
      - JWT_SECRET=${JWT_SECRET}
      - UNIFI_CONTROLLER_URL=${UNIFI_CONTROLLER_URL}
      - UNIFI_USERNAME=${UNIFI_USERNAME}
      - UNIFI_PASSWORD=${UNIFI_PASSWORD}
    networks:
      - hotspot-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=hotspotdb
      - POSTGRES_USER=hotspotuser
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotspot-network

volumes:
  postgres_data:

networks:
  hotspot-network:
    driver: bridge